---
.github:
  default_branch: main
  description: SovereignCloudStack/.github is a special repository. The /profile/README.md will appear on the organization's profile!
  homepage: 'https://github.com/SovereignCloudStack'
  topics:
    - github
  archived: false
  has_issues: true
  has_projects: false
  has_wiki: false
  private: false
  delete_branch_on_merge: true
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: true
  teams: []
  collaborators: []
  branch_protections:
    - branch: "main"
      template: "main"
